### ISSUE TITLE
Compilation Errors (error: use of undeclared identifier 'KBUILD_MODNAME')

### ISSUE THREAD

**Issue by yiwenzhang92** [SlugLab/CXLMemSim#1]
I'm getting an error when I tried to compile CXLMemSim. I'm using Ubuntu22.04 with kernel version 5.19.1-051901-generic.
I simply used cmake . && make.
Following is the error message I got:

FAILED: CMakeFiles/collectmmap_bpf /users/yiwenzhg/CXLMemSim/build/CMakeFiles/collectmmap_bpf
cd /users/yiwenzhg/CXLMemSim/build && /usr/lib/llvm-14/include/../bin/clang -S -nostdinc -I/lib/modules/5.19.1-051901-generic/build//arch/x86/include -I/lib/modules/5.19.1-051901-generic/build//arch/x86/include/uapi -I/lib/modules/5.19.1-051901-generic/build//arch/x86/include/generated -I/lib/modules/5.19.1-051901-generic/build//arch/x86/include/generated/uapi -I/lib/modules/5.19.1-051901-generic/build//include -I/lib/modules/5.19.1-051901-generic/build//include/uapi -I/lib/modules/5.19.1-051901-generic/build//include/generated/uapi -I/lib/modules/5.19.1-051901-generic/build//tools/testing/selftests/bpf -include /lib/modules/5.19.1-051901-generic/build//include/linux/kconfig.h -Werror -D__KERNEL__ -D__ASM_SYSREG_H -D__BPF_TRACING__ -D__TARGET_ARCH_x86 -Wno-unused-value -Wno-pointer-sign -Wno-compare-distinct-pointer-types -Wno-gnu-variable-sized-type-not-at-end -Wno-tautological-compare -Wno-unknown-warning-option -Wno-address-of-packed-member -O2 -g -emit-llvm -c /users/yiwenzhg/CXLMemSim/src/collectmmap.c -o /users/yiwenzhg/CXLMemSim/build/collectmmap.ll && /usr/lib/llvm-14/include/../bin/llc -march=bpf -filetype=obj -o /users/yiwenzhg/CXLMemSim/build/collectmmap.o /users/yiwenzhg/CXLMemSim/build/collectmmap.ll
In file included from /users/yiwenzhg/CXLMemSim/src/collectmmap.c:1:
In file included from /lib/modules/5.19.1-051901-generic/build//include/linux/filter.h:26:
In file included from /lib/modules/5.19.1-051901-generic/build//include/net/sch_generic.h:21:
/lib/modules/5.19.1-051901-generic/build//include/net/flow_offload.h:345:4: error: use of undeclared identifier 'KBUILD_MODNAME'
                        NL_SET_ERR_MSG_MOD(extack, "Mixing HW stats types for actions is not supported");

Using the build commands provided in CXLMemSim/artifact/build_and_run_all.sh gives the same error, together with a missing jemalloc error.

Any hint would be very helpful. Thanks!

**Comment by victoryang00** [comment]
Just comment out the line with `NL_SET_ERR_MSG_MOD`.
