### ISSUE TITLE
perf_event_open: No such process

### ISSUE THREAD

**Issue by ritaru** [SlugLab/CXLMemSim#10]
I tried the git workflow and built CXLMemSim, CXLMemSimSock, libCXLMemSimHook.so.

However, no matter what microbench I run, I get these results.

```text
rita@rita-server:~/CXLMemSim/build$ sudo ./CXLMemSim -t ./microbench/ld -i 5 -c 0,2 -d 85 -b 10,10 -l 100,100 -c 100,100 -w 85.5,86.5,87.5,85.5,86.5,87.5,88. -o "(1,(2,3))"
perf_event_open: No such process
terminate called without an active exception
Aborted
```

The system configuration is as below.

CPU: Intel i9-10980XE (avx512f capable)
MEM: Samsung DDR4 2666MHz 32GB * 8 
OS: Ubuntu 22.04.4 LTS
Kernel: 5.15.0-91-generic
gcc: 13.1.0
g++: same as gcc

**Comment by ritaru** [comment]
Okay, I did not run cmake on microbench directory.

After this, I get a message of runtime errors.

```text
rita@rita-server:~/CXLMemSim/build$ sudo LOGV=1 ./CXLMemSim -t ../microbench/ld -i 5 -c 0,2 -d 85 -b 10,10 -l 100,100 -c 100,100 -w 85.5,86.5,87.5,85.5,86.5,87.5,88. -o "(1,(2,3))"
/home/rita/CXLMemSim/src/main.cc:126 int main(int, char**) (CXLSwitch 1 (CXLMemExpander 1,CXLMemExpander 2))(CXLMemExpander 0)
 /home/rita/CXLMemSim/src/monitor.cpp:96 int Monitors::enable(uint32_t, uint32_t, bool, uint64_t, int32_t) pid 0[tgid=1376670, tid=1376670] monitoring start
 /home/rita/CXLMemSim/src/helper.cpp:65 PerfConfig Helper::detect_model(uint32_t, const std::vector<std::__cxx11::basic_string<char> >&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) Detecting model...85
terminate called after throwing an instance of 'std::runtime_error'
  what():  open
Aborted
```

**Comment by victoryang00** [comment]
This CPUID is not supported, you can try to add a id and corresponding PMU location in helper.cpp and continue.

**Comment by pudding-art** [comment]
I also met same question when I run instruction below:
$~/workspace/CXLMemSim$ sudo LOGV=1 ./CXLMemSim -t ./microbench/ld -i 5 -c 1 -d 85 -b 10,10 -l 100,100 -c 100,10
0 -w 85.5,86.5,87.5,85.5,86.5,87.5,88. -o "(1,(2,3))"
/home/workspace/CXLMemSim/src/main.cc:126 int main(int, char**) (CXLSwitch 1 (CXLMemExpander 1,CXLMemExpander 2))(CXLMemExpander 0)
 /home/workspace/CXLMemSim/src/main.cc:177 int main(int, char**) Exec: failed to create target process
 perf_event_open: No such process
terminate called without an active exception

CPU type: Intel(R) Xeon(R) Silver 4410Y
CPU ID:143
OS: Ubuntu 22.04.4 LTS
gcc: 13.1.0
g++: same as gcc

I see CPU type in helper.hh:
"enum { CPU_MDL_BDX = 63, CPU_MDL_SKX = 85, CPU_MDL_SPR = 143, CPU_MDL_ADL = 151, CPU_MDL_END = 0x0ffff };"
CPU_MDL_SPR is supported, but I also met the same question, how can I fix it?

**Comment by pudding-art** [comment]
> I also met same question when I run instruction below:  /workspace/CXLMemSim sudo LOGV=1 ./CXLMemSim -t ./microbench/ld -i 5 -c 1 -d 85 -b 10,10 -l 100,100 -c 100,10 0 -w 85.5,86.5,87.5,85.5,86.5,87.5,88. -o "(1,(2,3))" /home/workspace/CXLMemSim/src/main.cc:126 int main(int, char**) (CXLSwitch 1 (CXLMemExpander 1,CXLMemExpander 2))(CXLMemExpander 0) /home/workspace/CXLMemSim/src/main.cc:177 int main(int, char**) Exec: failed to create target process perf_event_open: No such process terminate called without an active exception
> 
> CPU type: Intel(R) Xeon(R) Silver 4410Y CPU ID:143 OS: Ubuntu 22.04.4 LTS gcc: 13.1.0 g++: same as gcc
> 
> I see CPU type in helper.hh: "enum { CPU_MDL_BDX = 63, CPU_MDL_SKX = 85, CPU_MDL_SPR = 143, CPU_MDL_ADL = 151, CPU_MDL_END = 0x0ffff };" CPU_MDL_SPR is supported, but I also met the same question, how can I fix it?

`~/workspace/CXLMemSim$ cat  /proc/sys/kernel/perf_event_paranoid
1`

**Comment by pudding-art** [comment]
> I also met same question when I run instruction below:  /workspace/CXLMemSim sudo LOGV=1 ./CXLMemSim -t ./microbench/ld -i 5 -c 1 -d 85 -b 10,10 -l 100,100 -c 100,10 0 -w 85.5,86.5,87.5,85.5,86.5,87.5,88. -o "(1,(2,3))" /home/workspace/CXLMemSim/src/main.cc:126 int main(int, char**) (CXLSwitch 1 (CXLMemExpander 1,CXLMemExpander 2))(CXLMemExpander 0) /home/workspace/CXLMemSim/src/main.cc:177 int main(int, char**) Exec: failed to create target process perf_event_open: No such process terminate called without an active exception
> 
> CPU type: Intel(R) Xeon(R) Silver 4410Y CPU ID:143 OS: Ubuntu 22.04.4 LTS gcc: 13.1.0 g++: same as gcc
> 
> I see CPU type in helper.hh: "enum { CPU_MDL_BDX = 63, CPU_MDL_SKX = 85, CPU_MDL_SPR = 143, CPU_MDL_ADL = 151, CPU_MDL_END = 0x0ffff };" CPU_MDL_SPR is supported, but I also met the same question, how can I fix it?

` cat  /proc/sys/kernel/perf_event_paranoid
1`， but it also doesn't work.

**Comment by pudding-art** [comment]
> > I also met same question when I run instruction below:  /workspace/CXLMemSim sudo LOGV=1 ./CXLMemSim -t ./microbench/ld -i 5 -c 1 -d 85 -b 10,10 -l 100,100 -c 100,10 0 -w 85.5,86.5,87.5,85.5,86.5,87.5,88. -o "(1,(2,3))" /home/workspace/CXLMemSim/src/main.cc:126 int main(int, char**) (CXLSwitch 1 (CXLMemExpander 1,CXLMemExpander 2))(CXLMemExpander 0) /home/workspace/CXLMemSim/src/main.cc:177 int main(int, char**) Exec: failed to create target process perf_event_open: No such process terminate called without an active exception
> > CPU type: Intel(R) Xeon(R) Silver 4410Y CPU ID:143 OS: Ubuntu 22.04.4 LTS gcc: 13.1.0 g++: same as gcc
> > I see CPU type in helper.hh: "enum { CPU_MDL_BDX = 63, CPU_MDL_SKX = 85, CPU_MDL_SPR = 143, CPU_MDL_ADL = 151, CPU_MDL_END = 0x0ffff };" CPU_MDL_SPR is supported, but I also met the same question, how can I fix it?
> 
> ` cat /proc/sys/kernel/perf_event_paranoid 1`， but it also doesn't work.



 in main.cc:
/** Create target process */
    Helper::detach_children();
    auto t_process = fork();
    if (t_process < 0) {
        LOG(ERROR) << "Fork: failed to create target process";
        exit(1);
    } else if (t_process == 0) {
        execv(filename, args); // taskset in lpace
        LOG(ERROR) << "Exec: failed to create target process\n";
        exit(1);
    }

**Comment by victoryang00** [comment]
`LOGV=1 ./CXLMemSim -t ./microbench/ld -i 5 -c 0,2 -d 85 -w 85.5,86.5,87.5,85.5,86.5,87.5,88. -o "(1,(2,3))"` remove bw works fine.

**Comment by victoryang00** [comment]
Total delays' calculation is buggy, if you have time, you can tune a better model with recorded information.
