### ISSUE TITLE
perf_event_open: Operation not supported

### ISSUE THREAD

**Issue by xywangbuaa** [SlugLab/CXLMemSim#14]
My previous steps can be compiled successfully, but when running, no matter how I configure it, the following error message is displayed, how can I solve it?

root@ubuntu:/usr/src/CXLMemSim/build# sudo LOGV=1 ./CXLMemSim -t ./microbench/malloc
/usr/src/CXLMemSim/src/main.cc:126 int main(int, char**) (CXLSwitch 1 (CXLMemExpander 1,CXLMemExpander 2))(CXLMemExpander 0)
perf_event_open: Operation not supported
terminate called without an active exception
 /usr/src/CXLMemSim/src/main.cc:177 int main(int, char**) Exec: failed to create target process
 Aborted

**Comment by victoryang00** [comment]
Not sure if you have the `/proc/sys/kernel/perf_event_paranoid` set right, it should be -1.

**Comment by xywangbuaa** [comment]
Thanks for your answers，I have changed the parameter of "perf_event_paranoid" with "-1", but it still occurs the error: "perf_event_open: Operation not supported
terminate called without an active exception"

**Comment by victoryang00** [comment]
I think it's kernel switch off the [PEBS](https://stackoverflow.com/questions/70493444/using-perf-event-open-to-get-sample-address-however-the-addr-0)?

**Comment by xywangbuaa** [comment]
Yes，I use VMware workstation and configuration is ubuntu 22.04, linux kernel verison is 6.5.0-41-generic, perf verison is 6.5.13.

**Comment by victoryang00** [comment]
We currently do not support VM.
