### ISSUE TITLE
Have latency been injected for async memory instructions as well?

### ISSUE THREAD

**Issue by GrayXu** [SlugLab/CXLMemSim#15]
Thank you for your efforts on this project!  
I'd like to ask whether latency has been injected for async memory instructions as well? like SW prefetch

**Comment by victoryang00** [comment]
Yes and No, we rely on a synthetic linear model for L2 writebacks and L3 misses PMU to predict the latency, which may include SW prefetch as traffic.

**Comment by GrayXu** [comment]
Thank you for your reply!  
I konw the behavior of SW prefetch is also monitored by PMU. But SW prefetch is non-blocking, and its impact on the foreground (or overall) depends on many factors.   
I'm just curious, is the delay penalty here also estimated by the model? So it's like an average state?

**Comment by victoryang00** [comment]
Yes, it's sort of like the average state according to the PMU.
