### ISSUE TITLE
Request for Detailed Running Instructions for CXLMemSim

### ISSUE THREAD

**Issue by Super-JiaMing** [SlugLab/CXLMemSim#16]
I have successfully compiled and generated the executable file for CXLMemSim. However, I am encountering issues when trying to run the "user input" as mentioned in the instructions. The execution is not successful, and I would appreciate it if you could provide more detailed running instructions.
Thank you very much for your assistance.

**Comment by 2117209** [comment]
CXLMemSim/src/main.cc:126 int main(int, char**) (CXLSwitch 1 (CXLMemExpander 1,CXLMemExpander 2))(CXLMemExpander 0)
 /root/lionelhliu/cxl/CXLMemSim/src/monitor.cpp:96 int Monitors::enable(uint32_t, uint32_t, bool, uint64_t, int32_t) pid 0[tgid=267639, tid=267639] monitoring start
 /root/lionelhliu/cxl/CXLMemSim/src/helper.cpp:65 PerfConfig Helper::detect_model(uint32_t, const std::vector<std::__cxx11::basic_string<char> >&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) Detecting model...143
terminate called after throwing an instance of 'std::runtime_error'
  what():  open
Aborted (core dumped)

**Comment by 2117209** [comment]
> o

"user input"  two  c"

**Comment by victoryang00** [comment]
CXLMemSim is not validated with real device yet.
