### ISSUE TITLE
Setting pmu_name, pmu_config1, pmu_config2

### ISSUE THREAD

**Issue by beom115** [SlugLab/CXLMemSim#17]
I want to measure dtlb_miss & hit rate. My cpu model is skylake and how can i set pmu_config1, config2 to measure it?
Is there any reference to get the information of raw encoding which i want to measure?

**Comment by victoryang00** [comment]
Refer to https://perfmon-events.intel.com/ and https://cdrdv2-public.intel.com/679093/639778%20ICX%20UPG%20v1.pdf
