### ISSUE TITLE
what is CXL-MEM-Simulator

### ISSUE THREAD

**Issue by YFR718** [SlugLab/CXLMemSim#2]
when i run `LOGV=1 ./CXL-MEM-Simulator -t ./microbench/many_calloc -i 5 -c 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14`
output: `-bash: ./CXL-MEM-Simulator: No such file or directory`

so,what is the file of CXL-MEM-Simulator,and how can I run it?

**Comment by victoryang00** [comment]
You need to follow the [cmake.yml](https://github.com/SlugLab/CXLMemSim/blob/main/.github/workflows/cmake.yml) to install.

Specifically, you need first install the `sudo apt install llvm-dev clang libbpf-dev libclang-dev libcxxopts-dev libfmt-dev librange-v3-dev`.

Then you need to install for upper version of libbpf using `wget http://launchpadlibrarian.net/605552811/libbpf0_0.8.0-1_amd64.deb && wget http://launchpadlibrarian.net/605552807/libbpf-dev_0.8.0-1_amd64.deb && sudo dpkg -i ./libbpf0_0.8.0-1_amd64.deb && sudo dpkg -i ./libbpf-dev_0.8.0-1_amd64.deb` and `sudo sed -i 's/NL_SET_ERR_MSG_MOD/\/\/NL_SET_ERR_MSG_MOD/g' /usr/src/linux-headers-*/include/net/flow_offload.h`

Then `cmake -B ./build -DCMAKE_BUILD_TYPE=Debug`, you will see the CXL-MEM-Simulator in thee sub dereictory

**Comment by orangewcz2000** [comment]
> You need to follow the [cmake.yml](https://github.com/SlugLab/CXLMemSim/blob/main/.github/workflows/cmake.yml) to install.
> 
> Specifically, you need first install the `sudo apt install llvm-dev clang libbpf-dev libclang-dev libcxxopts-dev libfmt-dev librange-v3-dev`.
> 
> Then you need to install for upper version of libbpf using `wget http://launchpadlibrarian.net/605552811/libbpf0_0.8.0-1_amd64.deb && wget http://launchpadlibrarian.net/605552807/libbpf-dev_0.8.0-1_amd64.deb && sudo dpkg -i ./libbpf0_0.8.0-1_amd64.deb && sudo dpkg -i ./libbpf-dev_0.8.0-1_amd64.deb` and `sudo sed -i 's/NL_SET_ERR_MSG_MOD/\/\/NL_SET_ERR_MSG_MOD/g' /usr/src/linux-headers-*/include/net/flow_offload.h`
> 
> Then `cmake -B ./build -DCMAKE_BUILD_TYPE=Debug`, you will see the CXL-MEM-Simulator in the build dereictory.

Hello, I tried according to your description, but I didn't see CXL-MEM-Simulator in the build dereictory.

**Comment by victoryang00** [comment]
> > You need to follow the [cmake.yml](https://github.com/SlugLab/CXLMemSim/blob/main/.github/workflows/cmake.yml) to install.
> > Specifically, you need first install the `sudo apt install llvm-dev clang libbpf-dev libclang-dev libcxxopts-dev libfmt-dev librange-v3-dev`.
> > Then you need to install for upper version of libbpf using `wget http://launchpadlibrarian.net/605552811/libbpf0_0.8.0-1_amd64.deb && wget http://launchpadlibrarian.net/605552807/libbpf-dev_0.8.0-1_amd64.deb && sudo dpkg -i ./libbpf0_0.8.0-1_amd64.deb && sudo dpkg -i ./libbpf-dev_0.8.0-1_amd64.deb` and `sudo sed -i 's/NL_SET_ERR_MSG_MOD/\/\/NL_SET_ERR_MSG_MOD/g' /usr/src/linux-headers-*/include/net/flow_offload.h`
> > Then `cmake -B ./build -DCMAKE_BUILD_TYPE=Debug`, you will see the CXL-MEM-Simulator in the build dereictory.
> 
> Hello, I tried according to your description, but I didn't see CXL-MEM-Simulator in the build dereictory.

The main branch is still in development

**Comment by wogusrla** [comment]
Hello :)
Are you still in developing..?
I also couldn't find that directory.

**Comment by victoryang00** [comment]
Nope, we stopped developing the repo, but CXLMemSim should be found as noted.
