### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by Wu0103** [SlugLab/CXLMemSim#4]
Thanks for your great work.
Just wondering if it's possible for you to provide a docker image. I tried many times to get it running, but always come into new problems every time. Having a docker image would greatly increase convenience.
Thanks!

**Comment by victoryang00** [comment]
I guess the ebpf is hard to run in the docker without privilege, but I will make a docker image. If you have problem compiling or running. please refer to github action.

**Comment by victoryang00** [comment]
Debug and take a look at this https://linux.die.net/man/2/perf_event_open. Normally it's CPU not -1 or PID has no permission.
