### ISSUE TITLE
Is CPU model important?

### ISSUE THREAD

**Issue by quyifei23** [SlugLab/CXLMemSim#5]
my cpu model is 141,and it is not in
`enum { CPU_MDL_BDX = 63, CPU_MDL_SKX = 85, CPU_MDL_SPR = 143, CPU_MDL_ADL = 151, CPU_MDL_END = 0x0ffff };`
so when i run the program,it stop like
```
PerfConfig Helper::detect_model(ui2_t, const std::vector<std::__cxx11::basic_string<char> >&, const std::vector<long ugned int>&, const std::vector<long unsigned int>&) Failed to execute. This CPU model not supported. Refer to perfmon or pcm to add support
terminate called without an active exception
```
can i run this program?

**Comment by victoryang00** [comment]
Tiger lake should be the same with ADL, you can change ADL's 151 to 141 to run the program.
