### ISSUE TITLE
How does CXLMemSim implement coherence？

### ISSUE THREAD

**Issue by JimmyWong1998** [SlugLab/CXLMemSim#8]
Hi,

As the title describe, how does CXLMemSim implement coherence？Is there any directory or instruction to keep the coherence?

Best wishes,
Jimmy

**Comment by victoryang00** [comment]
We use the original CPU's performance to emulate the CPU, we only add a penalty to the original program with observed coherency overhead. In short, we observe the PMU hitm rate and miss rate to know how much is hit by coherency, or miss by coherency to add to the penalty. The penalty model is synthetical, which is a linear model.
